## **Introducción a NumPy:**

NumPy (Numerical Python) es una librería de Python que se utiliza ampliamente en el procesamiento numérico y científico de datos. Proporciona una estructura de datos llamada "array" (arreglo) que es eficiente en términos de almacenamiento y cómputo, y ofrece una amplia gama de funciones para trabajar con estos arreglos. A continuación, exploraremos los conceptos clave relacionados con NumPy.

### **¿Qué es NumPy?**

NumPy es una librería de código abierto en Python que se utiliza para realizar operaciones matemáticas y lógicas en arreglos multidimensionales o matrices. Está diseñada para trabajar con datos numéricos y es ampliamente utilizada en el ámbito de la ciencia de datos, la ingeniería y la computación científica debido a su eficiencia y facilidad de uso.

### **Creación de arrays NumPy:**

NumPy permite crear arrays multidimensionales de manera eficiente. Puedes crear arrays NumPy utilizando listas de Python o mediante funciones específicas de NumPy.

Ejemplo de creación de un array NumPy:

In [ ]:
lista=[2,5,9,7,3,4,6]
lista

[2, 5, 9, 7, 3, 4, 6]

In [ ]:
import numpy as np
#crear un arreglo
mi_array=np.array([2,5,9,7,3,4,6])
print(mi_array)

[2 5 9 7 3 4 6]


In [ ]:
lista2=[1,2,3,4,5,6,7]
mi_array2=np.array(lista2)
print(mi_array2)

[1 2 3 4 5 6 7]


### **Operaciones básicas con arrays NumPy:**

NumPy proporciona numerosas operaciones matemáticas y aritméticas que se pueden realizar en arrays, incluyendo suma, resta, multiplicación y división, tanto elemento por elemento como a nivel de matriz.

Ejemplo de operaciones básicas con arrays NumPy:

In [ ]:
lista*2

[2, 5, 9, 7, 3, 4, 6, 2, 5, 9, 7, 3, 4, 6]

In [ ]:
mi_array*2

array([ 4, 10, 18, 14,  6,  8, 12])

In [ ]:
#Suma de arreglos
array1=np.array([1,2,3])
array2=np.array([9,8,7])

suma=array1+array2
suma

array([10, 10, 10])

In [ ]:
producto=array1*array2
producto

array([ 9, 16, 21])

### **Indexación y slicing en arrays NumPy:**

Puedes acceder a elementos individuales de un array NumPy utilizando la indexación, y también puedes realizar "slicing" para seleccionar subconjuntos de elementos.

Ejemplo de indexación y slicing en un array NumPy:

In [ ]:
#indexacion

array3=np.array([0,1,2,3,4,6,7,])
print("mi elemento en la posicion 2: ", array3[1] )

mi elemento en la posicion 2:  1


In [ ]:
#slicing
sub_array=array3[1:4]
print(sub_array)

[1 2 3]


### **Ejemplos de operaciones matriciales con NumPy:**

NumPy es especialmente poderoso cuando se trata de operaciones matriciales. Puedes realizar multiplicación de matrices, transposición, cálculos de determinantes y mucho más de manera eficiente.

Ejemplo de multiplicación de matrices con NumPy:

In [ ]:
matriz1=np.array([[1,2],[3,4]])
print(matriz1)

[[1 2]
 [3 4]]


In [ ]:
matriz2=np.array([[5,6],[7,8]])
print(matriz2)

[[5 6]
 [7 8]]


In [ ]:
#multiplicacion de matrices
resultado=np.dot(matriz1,matriz2)
resultado

array([[19, 22],
       [43, 50]])

### **Problema: Cálculo de Estadísticas en Datos de Ventas**

Supongamos que tienes un conjunto de datos de ventas de productos en una tienda durante varios meses. Cada fila del conjunto de datos representa una venta y contiene información sobre el producto vendido, la cantidad vendida y el precio unitario. Tu objetivo es realizar algunas estadísticas básicas en estos datos utilizando NumPy.

In [ ]:
#datos de venta (producto, cantidad, precio unitario)
ventas=np.array([
    ["Shampoo", 100, 24000],
    ["Crema de manos", 50, 13000],
    ["Jabón", 75, 6000],
    ["Cera para el cabello", 120, 18000],
    ["Protector solar", 60, 82000]
])

#calcular el total de ventas para cada producto
total_ventas= ventas[:,1].astype(float)* ventas[:,2].astype(float)

#calcular el total de ventas en general
total_ventas_general=np.sum(total_ventas)

#calcular el producto mas vendido
producto_mas_vendida=ventas[np.argmax(ventas[:,1].astype(int)),0]

#calcular valor pomedio por producto
precio_promedio_por_productos=np.mean(ventas[:,2].astype(float))

#imprimir resultados
print("Total de ventas por producto: ")
print(total_ventas)
print("\nTotal de ventas en general: ", total_ventas_general)
print("\nProducto mas vendido: ", producto_mas_vendida)
print("\nPrecio promedio por producto: ", precio_promedio_por_productos)

Total de ventas por producto: 
[2400000.  650000.  450000. 2160000. 4920000.]

Total de ventas en general:  10580000.0

Producto mas vendido:  Cera para el cabello

Precio promedio por producto:  28600.0


In [ ]:
# Para matrices con numpy
# [fila,columna]
# [:, 0]:
    # El : selecciona todas las filas.
    # El 0 selecciona la primera columna.

# [1, :]:

    # El 1 selecciona la segunda fila (recuerda que los índices empiezan en 0).
    # El : selecciona todas las columnas de esa fila.